5 '        ***** THIS IS THE PROGRAM CALLED "WRTSTRNG.BAS" *****
10 OPEN"O",1,"STRINGS.FIL"
20 DIM OW$(22),RW$(22),LO(22),LR(22),A$(20),K$(44),B$(27),M$(20)
30 DATA .," . ",","," . ",?," . ",!," . ",MOM,MOTHER,DAD,   FATHER,DONT,DON'T,CANT,CAN'T,WONT,WON'T,DREAMED,DREAMT,   DREAMS,DREAM,I,YOU,YOU,I,ME,YOU,MY,*OUR,YOUR,MY,MYSELF,   *OURSELF,YOURSELF,MYSELF,I'M,*OU'RE,YOU'RE,I'M,AM,ARE,   WERE,WAS
40 FOR I=1 TO 22:READ OW$(I),RW$(I):LO(I)=LEN(OW$(I)):LR(I)=LEN(RW$(I)):NEXT
50 FOR I=5 TO 22:RW$(I)=" "+RW$(I)+" ":OW$(I)=" "+OW$(I)+" "
60 LO(I)=LO(I)+2:LR(I)=LR(I)+2
70 NEXT
80 DATA IS,ARE,ARE,WAS,MOTHER,FATHER,SISTER,BROTHER,WIFE,    HUSBAND,CHILDREN,WANT,NEED,SAD,UNHAPPY,DEPRESSED,SICK,    HAPPY,ELATED,GLAD,BETTER,FEEL,THINK,BELIEVE,WISH,CAN'T,    CANNOT
90 FOR I=1 TO 27:READ B$(I):B$(I)=" "+B$(I)+" ":NEXT
100 DATA COMPUTER,COMPUTERS,MACHINE,MACHINES,NAME,ALIKE,LIKE,    SAME,REMEMBER,DREAMT,DREAM,IF,EVERYBODY,EVERYONE,NOBODY,    NO ONE,WAS,YOUR,ALWAYS,SORRY,ARE,ARE,BECAUSE,CAN,CERTAINLY,    YES,DEUTSCH,ESPANOL,FRANCAIS,ITALIANO,HELLO,HOW,WHAT
110 DATA WHEN,WHO,I,I'M,MAYBE,PERHAPS,MY,NO,WHY,YOU,YOU'RE
120 FOR I=1 TO 44:READ K$(I):K$(I)=" "+K$(I)+" ":NEXT
130 FOR I=1 TO 22:WRITE#1,OW$(I),RW$(I),LO(I),LR(I):NEXT
140 FOR I=1 TO 27:WRITE#1,B$(I):NEXT
150 FOR I=1 TO 44:WRITE#1,K$(I):NEXT
160 END
